name: lambda-alb-helloworld-test
on: [push,pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: unit-testing
        run: |
          python3 -V # Print python version for debug
          pip3 install pytest
          pip3 install -r requirements.txt
          pytest --verbose
